module.exports = {
    custom: require("./custom"),
    elixire: require("./elixire"),
    ftp: require("./ftp"),
    imgur: require("./imgur"),
    magiccap: require("./magiccap"),
    novus: require("./lunus"),
    pomf: require("./pomf"),
    reupload: require("./reupload"),
    s3: require("./s3"),
    sharex: require("./sharex"),
    ultrashare: require("./ultrashare"),
    sftp: require("./sftp"),
    dropbox: require("./dropbox"),
}
